c_coding@V-3491: ~/CCD$ gcc helloout.c 
c_coding@V-3491: ~/CCD$ ./a.out 

HELLO WORLD
I AM SACHIN CHAURASIYA
THIS IS MY FIRST PROGRAM OF MY LIFE
AND I AM JUST STARTING FROM BEGINING...

c_coding@V-3491: ~/CCD$ exit